dist: focal
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.8'
install:
- pip install coveralls
- pip install -r .circleci/requirements.hwtGraph.txt
- python setup.py install
- rm -r node_modules
script:
- coverage run --source=sphinx_hwt -m tests.all
deploy:
  provider: pypi
  user: nic30
  password:
    secure: k+J+xbOp4n4DiRy3Th7JaNZGdHz9d5nCxJnynnujabXQM9pD9V8eAqVdiuG0gzonSr4u0CLz/3oHrjOE9M7K/BzQUyTERKecMH8A1OQ5gx3zBIevZjYoEeo8We9cn97NqeKXLIY7Co5qDV/GEkyp+bXS5NgUHFb3wZGThVgoAA/zEbinKIIA/aNaUDgUrOHDkEVgIYd10j4mNyuxyWL2zbMxGDpUh9uurbmiESWlJ4JDAcRA054BjpXPnOYawzcQHFJEdIqPni0TyV8RR7T0BVqhJH5CQHXriAei1AQmObSFOfNOa3FJnJdtG7vm5P5KZDWI++7o+j+Z0WN717mbhEaCBcpqwnQP3gQuQZo5Pdth3N1xJ5QOgoAkbQCvhRvCrjo6wxSDvgylPJaStTVobFw7ttWLe4vI1c95pnWE49B1VOxG/ddZL4HTc+wujBDIqAR+onbMcfZsrvQTVMlkDhRbhcvVmfO58vlT9ISZfHENlm7vj7ytf0Ak51HXo5WWZCbv1/cYP4m2Gcx9cUr+TdrFRLT2raU5RHtKyVvSvLwSWt0V6TeEvMOZeW6U9H68js/fpsFYALRc1Y0gmA9MdRmpSA8OHCukCIdERP0P8ptVCrNNvrr8xylf5ce3jUMt5HInSZwIvuEY2fR0f1pstXpNuuLRz/K115CYAuJ7DaI=
  on:
    tags: true
    branch: master
after_success:
- coveralls
